# Usage:
#   mamba env create -f conda_environment.yaml

name: rdy2cpl

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>3.6
  - pip
  - mpi4py
  - openmpi
  - numpy
  - netcdf4
  - pyaml
  - pip:
    - scriptengine
