# Usage:
#   mamba env create -f conda_environment.yml

name: rdy2cpl

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.7
  - pip
  - mpi4py
  - openmpi
  - numpy
  - netcdf4
  - pyaml
